apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  selector:
    matchLabels:
      app: goserver
  replicas: 2
  template:
    metadata:
      labels:
        app: "goserver"
    spec:
      containers:
        - name: goserver
          image: "thulerjoao/hello-go:v8"
          envFrom:
            - configMapRef:
                name: goserver-env
            - secretRef:
                name: goserver-secret

          volumeMounts:
            - mountPath: "/go/myfamily" #onde será montado o voulume
              name: config #mesmo nome do volume abaixo

      volumes:
        - name: config
          configMap: 
            name: configmap-family
            items:
            - key: members
              path: "family.txt"